### ISSUE TITLE
Hi Mibarg

### ISSUE THREAD

**Issue by amlwwalker** [mibarg/crd#2]
I sincerely apologise for contacting you in this absurd way!
Hi, by the way, I am actually interested in your Sealed project - working on using python native operators on the PySeal HE framework. I promise I did dig around to find a more conventional way to contact you, so I hope this doesn't irritate you too much.

Couple of things - the first is you have put a comment that you are looking for support to port it to Seal 3.0 - I would be interested to discuss more here, however I also wanted to see if I could get a bit of support porting one of the original examples from PySeal (arrays/matrix of data) to Sealed. I am currently getting my head around the wrappers you have written and it would be really helpful to be able to ask you a couple of questions - as a result for you, I would happily write up the documentation for the project. I'm not sure the best way to communicate but this certainly isn't it! :joy: 

Thanks
Alex

**Comment by mbrg** [comment]
Hi! I'm embarrassed to say your message got lost among GitHub notifications, and I'm finding it now about a year later. This is probably no longer relevant, but I would be happy to hear where you ended up. I've sent you an email, let's get in touch.
